checkpoint: /scratch/work/jayawin1/article_4/videosaur/videosaur/checkpoints/videosaur_dinov2.ckpt
model_config: /scratch/work/jayawin1/article_4/videosaur/configs/videosaur/ytvis_dinov2.yml
n_slots_min: 4
input:
  folder: '/scratch/work/jayawin1/article_4/videosaur/cadc_test'
  type: video
  transforms:
    use_movi_normalization: false
    dataset_type: video
    input_size: 518
output:
  save_path: /scratch/work/jayawin1/article_4/videosaur/test_videos_output/kitti_sample_output.gif #PH
