checkpoint: /PATH/TO/DIR/checkpoints/videosaur_dinov2.ckpt #TODO change
model_config: /PATH/TO/DIR/configs/videosaur/ytvis_dinov2.yml #TODO change
n_slots_min: 4 
input:
  folder: /PATH/TO/DIR/waymo/waymo-video-tfds-40 #TODO change
  type: video
  transforms:
    use_movi_normalization: false
    dataset_type: video
    input_size: 518
output:
  save_folder: /PATH/TO/DIR/waymo/unsupervised_inference_results #TODO change