checkpoint: /scratch/work/jayawin1/article_4/videosaur/videosaur/checkpoints/videosaur_dinov2.ckpt
model_config: /scratch/work/jayawin1/article_4/videosaur/configs/videosaur/ytvis_dinov2.yml
n_slots: 6
input:
  path: /scratch/work/jayawin1/article_4/videosaur/test_videos/waymo_data_sample_10.mp4
  folder: /scratch/work/jayawin1/article_4/videosaur/test_videos
  type: video
  transforms:
    use_movi_normalization: false
    dataset_type: video
    input_size: 518
output:
  save_path: /scratch/work/jayawin1/article_4/videosaur/test_videos_output/waymo_sample_output.gif
  save_folder: /scratch/work/jayawin1/article_4/videosaur/test_videos_output